version: '3.8'

services:
  web:
    build: .
    command: uvicorn app:app --reload --port 8000 --host 0.0.0.0
    ports:
      - 8000:8000

  react:
    build:
      context: ./Frontend/synthesis-web-app
    ports:
      - 3000:80